import { gql } from 'graphql-request'
import { defineStore } from 'pinia'
import { ref } from 'vue'
import { gqlClient } from '../utils/graphql.js'
import { useLoadingStore } from './loadingStore.js'
import type { Facility, FacilitySearchFilters } from '~/typedefs/gqlTypes.js'
import { useTranslation } from '~/composables/useTranslation.js'
import { City, Region, Prefecture } from '~/typedefs/locationEnums.js'

export const useLocationsStore = defineStore('locationsStore', () => {
    const allCitiesEnglishList = ref<string[]>([])
    const allCitiesJapaneseList = ref<string[]>([])

    async function fetchLocations() {
        //set the loading visual state
        const loadingStore = useLoadingStore()
        loadingStore.setIsLoading(true)

        const facilitiesSearchResults = await queryFacilities()

        allCitiesEnglishList.value = facilitiesSearchResults.map(facility => facility.contact?.address.cityEn)
        allCitiesJapaneseList.value = facilitiesSearchResults.map(facility => facility.contact?.address.cityJa)

        //set the loading visual state back to normal
        loadingStore.setIsLoading(false)
    }

    return { allCitiesEnglishList, allCitiesJapaneseList, fetchLocations }
})

async function queryFacilities(): Promise<Facility[]> {
    try {
        const searchFacilitiesData = {
            filters: {
                limit: 1000,
                offset: 0,
                contact: undefined,
                createdDate: undefined,
                healthcareProfessionalIds: undefined,
                healthcareProfessionalName: undefined,
                nameEn: undefined,
                nameJa: undefined,
                orderBy: undefined,
                updatedDate: undefined
            } satisfies FacilitySearchFilters
        }

        const result = await graphQLClientRequestWithRetry<{ facilities: Facility[] }>(
            gqlClient.request.bind(gqlClient),
            searchFacilitiesQuery,
            searchFacilitiesData
        )

        return result.data.facilities ?? []
    } catch (error) {
        console.error(useTranslation('locationErrors.facilitiesDropdown'), ` ${JSON.stringify(error)}`)
        // eslint-disable-next-line no-alert
        alert(useTranslation('locationErrors.gettingData'))
        return []
    }
}

const searchFacilitiesQuery = gql`query QueryFacilities($filters: FacilitySearchFilters!) {
    facilities(filters: $filters) {
    id
    contact {
        address {
          cityJa
          cityEn
          }
        }
    }
}
`
export const regionsEnum: Region[] = [
    Region.Hokkaido, Region.Tohoku, Region.Kanto, Region.Chubu, Region.Kansai, Region.Chugoku,
    Region.Shikoku, Region.Kyushu, Region.Okinawa
]

export const prefecturesEnum: Prefecture[] = [
    Prefecture.Hokkaido, Prefecture.Aomori, Prefecture.Iwate, Prefecture.Miyagi,
    Prefecture.Akita, Prefecture.Yamagata, Prefecture.Fukushima, Prefecture.Ibaraki,
    Prefecture.Tochigi, Prefecture.Gunma, Prefecture.Saitama, Prefecture.Chiba,
    Prefecture.Tokyo, Prefecture.Kanagawa, Prefecture.Niigata, Prefecture.Toyama,
    Prefecture.Ishikawa, Prefecture.Fukui, Prefecture.Yamanashi, Prefecture.Nagano,
    Prefecture.Gifu, Prefecture.Shizuoka, Prefecture.Aichi, Prefecture.Mie,
    Prefecture.Shiga, Prefecture.Kyoto, Prefecture.Osaka, Prefecture.Hyogo,
    Prefecture.Nara, Prefecture.Wakayama, Prefecture.Tottori, Prefecture.Shimane,
    Prefecture.Okayama, Prefecture.Hiroshima, Prefecture.Yamaguchi, Prefecture.Tokushima,
    Prefecture.Kagawa, Prefecture.Ehime, Prefecture.Kochi, Prefecture.Fukuoka,
    Prefecture.Saga, Prefecture.Nagasaki, Prefecture.Kumamoto, Prefecture.Oita,
    Prefecture.Miyazaki, Prefecture.Kagoshima, Prefecture.Okinawa
]

// DisplayName for each
export const regionDisplayName: Record<Region, { en: string, ja: string }> = {
    [Region.Hokkaido]: { en: 'Hokkaido', ja: '北海道' },
    [Region.Tohoku]: { en: 'Tohoku', ja: '東北' },
    [Region.Kanto]: { en: 'Kanto', ja: '関東' },
    [Region.Chubu]: { en: 'Chubu', ja: '中部' },
    [Region.Kansai]: { en: 'Kansai', ja: '関西' },
    [Region.Chugoku]: { en: 'Chugoku', ja: '中国' },
    [Region.Shikoku]: { en: 'Shikoku', ja: '四国' },
    [Region.Kyushu]: { en: 'Kyushu', ja: '九州' },
    [Region.Okinawa]: { en: 'Okinawa', ja: '沖縄' }
}

export const prefectureDisplayName: Record<Prefecture, { en: string, ja: string }> = {
    [Prefecture.Hokkaido]: { en: 'Hokkaido', ja: '北海道' },
    [Prefecture.Aomori]: { en: 'Aomori', ja: '青森県' },
    [Prefecture.Iwate]: { en: 'Iwate', ja: '岩手県' },
    [Prefecture.Miyagi]: { en: 'Miyagi', ja: '宮城県' },
    [Prefecture.Akita]: { en: 'Akita', ja: '秋田県' },
    [Prefecture.Yamagata]: { en: 'Yamagata', ja: '山形県' },
    [Prefecture.Fukushima]: { en: 'Fukushima', ja: '福島県' },
    [Prefecture.Ibaraki]: { en: 'Ibaraki', ja: '茨城県' },
    [Prefecture.Tochigi]: { en: 'Tochigi', ja: '栃木県' },
    [Prefecture.Gunma]: { en: 'Gunma', ja: '群馬県' },
    [Prefecture.Saitama]: { en: 'Saitama', ja: '埼玉県' },
    [Prefecture.Chiba]: { en: 'Chiba', ja: '千葉県' },
    [Prefecture.Tokyo]: { en: 'Tokyo', ja: '東京都' },
    [Prefecture.Kanagawa]: { en: 'Kanagawa', ja: '神奈川県' },
    [Prefecture.Niigata]: { en: 'Niigata', ja: '新潟県' },
    [Prefecture.Toyama]: { en: 'Toyama', ja: '富山県' },
    [Prefecture.Ishikawa]: { en: 'Ishikawa', ja: '石川県' },
    [Prefecture.Fukui]: { en: 'Fukui', ja: '福井県' },
    [Prefecture.Yamanashi]: { en: 'Yamanashi', ja: '山梨県' },
    [Prefecture.Nagano]: { en: 'Nagano', ja: '長野県' },
    [Prefecture.Gifu]: { en: 'Gifu', ja: '岐阜県' },
    [Prefecture.Shizuoka]: { en: 'Shizuoka', ja: '静岡県' },
    [Prefecture.Aichi]: { en: 'Aichi', ja: '愛知県' },
    [Prefecture.Mie]: { en: 'Mie', ja: '三重県' },
    [Prefecture.Shiga]: { en: 'Shiga', ja: '滋賀県' },
    [Prefecture.Kyoto]: { en: 'Kyoto', ja: '京都府' },
    [Prefecture.Osaka]: { en: 'Osaka', ja: '大阪府' },
    [Prefecture.Hyogo]: { en: 'Hyogo', ja: '兵庫県' },
    [Prefecture.Nara]: { en: 'Nara', ja: '奈良県' },
    [Prefecture.Wakayama]: { en: 'Wakayama', ja: '和歌山県' },
    [Prefecture.Tottori]: { en: 'Tottori', ja: '鳥取県' },
    [Prefecture.Shimane]: { en: 'Shimane', ja: '島根県' },
    [Prefecture.Okayama]: { en: 'Okayama', ja: '岡山県' },
    [Prefecture.Hiroshima]: { en: 'Hiroshima', ja: '広島県' },
    [Prefecture.Yamaguchi]: { en: 'Yamaguchi', ja: '山口県' },
    [Prefecture.Tokushima]: { en: 'Tokushima', ja: '徳島県' },
    [Prefecture.Kagawa]: { en: 'Kagawa', ja: '香川県' },
    [Prefecture.Ehime]: { en: 'Ehime', ja: '愛媛県' },
    [Prefecture.Kochi]: { en: 'Kochi', ja: '高知県' },
    [Prefecture.Fukuoka]: { en: 'Fukuoka', ja: '福岡県' },
    [Prefecture.Saga]: { en: 'Saga', ja: '佐賀県' },
    [Prefecture.Nagasaki]: { en: 'Nagasaki', ja: '長崎県' },
    [Prefecture.Kumamoto]: { en: 'Kumamoto', ja: '熊本県' },
    [Prefecture.Oita]: { en: 'Oita', ja: '大分県' },
    [Prefecture.Miyazaki]: { en: 'Miyazaki', ja: '宮崎県' },
    [Prefecture.Kagoshima]: { en: 'Kagoshima', ja: '鹿児島県' },
    [Prefecture.Okinawa]: { en: 'Okinawa', ja: '沖縄県' }
}

export const cityDisplayName: Record<City, { en: string, ja: string }> = {
    // HOKKAIDO
    [City.HokkaidoSapporo]: { en: 'Sapporo', ja: '札幌市' },
    [City.HokkaidoHakodate]: { en: 'Hakodate', ja: '函館市' },
    [City.HokkaidoAsahikawa]: { en: 'Asahikawa', ja: '旭川市' },
    [City.HokkaidoKushiro]: { en: 'Kushiro', ja: '釧路市' },
    [City.HokkaidoObihiro]: { en: 'Obihiro', ja: '帯広市' },
    [City.HokkaidoKitami]: { en: 'Kitami', ja: '北見市' },
    [City.HokkaidoOtaru]: { en: 'Otaru', ja: '小樽市' },
    [City.HokkaidoMuroran]: { en: 'Muroran', ja: '室蘭市' },
    [City.HokkaidoTomakomai]: { en: 'Tomakomai', ja: '苫小牧市' },
    [City.HokkaidoWakkanai]: { en: 'Wakkanai', ja: '稚内市' },
    [City.HokkaidoNayoro]: { en: 'Nayoro', ja: '名寄市' },
    [City.HokkaidoBibai]: { en: 'Bibai', ja: '美唄市' },
    [City.HokkaidoAshibetsu]: { en: 'Ashibetsu', ja: '芦別市' },
    [City.HokkaidoEbetsu]: { en: 'Ebetsu', ja: '江別市' },
    [City.HokkaidoAkabira]: { en: 'Akabira', ja: '赤平市' },
    [City.HokkaidoMonbetsu]: { en: 'Monbetsu', ja: '紋別市' },
    [City.HokkaidoShibetsu]: { en: 'Shibetsu', ja: '士別市' },
    [City.HokkaidoNemuro]: { en: 'Nemuro', ja: '根室市' },
    [City.HokkaidoChitose]: { en: 'Chitose', ja: '千歳市' },
    [City.HokkaidoTakikawa]: { en: 'Takikawa', ja: '滝川市' },
    [City.HokkaidoSunagawa]: { en: 'Sunagawa', ja: '砂川市' },
    [City.HokkaidoUtashinai]: { en: 'Utashinai', ja: '歌志内市' },
    [City.HokkaidoFukagawa]: { en: 'Fukagawa', ja: '深川市' },
    [City.HokkaidoFurano]: { en: 'Furano', ja: '富良野市' },
    [City.HokkaidoNoboribetsu]: { en: 'Noboribetsu', ja: '登別市' },
    [City.HokkaidoEniwa]: { en: 'Eniwa', ja: '恵庭市' },
    [City.HokkaidoDate]: { en: 'Date', ja: '伊達市' },
    [City.HokkaidoKitahiroshima]: { en: 'Kitahiroshima', ja: '北広島市' },
    [City.HokkaidoIshikari]: { en: 'Ishikari', ja: '石狩市' },
    [City.HokkaidoHokuto]: { en: 'Hokuto', ja: '北斗市' },

    // AOMORI
    [City.AomoriAomori]: { en: 'Aomori', ja: '青森市' },
    [City.AomoriHirosaki]: { en: 'Hirosaki', ja: '弘前市' },
    [City.AomoriHachinohe]: { en: 'Hachinohe', ja: '八戸市' },
    [City.AomoriGoshogawara]: { en: 'Goshogawara', ja: '五所川原市' },
    [City.AomoriTowada]: { en: 'Towada', ja: '十和田市' },
    [City.AomoriMisawa]: { en: 'Misawa', ja: '三沢市' },
    [City.AomoriKuroishi]: { en: 'Kuroishi', ja: '黒石市' },
    [City.AomoriMutsu]: { en: 'Mutsu', ja: 'むつ市' },
    [City.AomoriTsugaru]: { en: 'Tsugaru', ja: 'つがる市' },
    [City.AomoriHirakawa]: { en: 'Hirakawa', ja: '平川市' },

    // IWATE
    [City.IwateMorioka]: { en: 'Morioka', ja: '盛岡市' },
    [City.IwateMiyako]: { en: 'Miyako', ja: '宮古市' },
    [City.IwateOfunato]: { en: 'Ofunato', ja: '大船渡市' },
    [City.IwateHanamaki]: { en: 'Hanamaki', ja: '花巻市' },
    [City.IwateKitakami]: { en: 'Kitakami', ja: '北上市' },
    [City.IwateKuji]: { en: 'Kuji', ja: '久慈市' },
    [City.IwateTono]: { en: 'Tono', ja: '遠野市' },
    [City.IwateIchinoseki]: { en: 'Ichinoseki', ja: '一関市' },
    [City.IwateRikuzentakata]: { en: 'Rikuzentakata', ja: '陸前高田市' },
    [City.IwateKamaishi]: { en: 'Kamaishi', ja: '釜石市' },
    [City.IwateNinohe]: { en: 'Ninohe', ja: '二戸市' },
    [City.IwateHachimantai]: { en: 'Hachimantai', ja: '八幡平市' },
    [City.IwateOshu]: { en: 'Oshu', ja: '奥州市' },
    [City.IwateTakizawa]: { en: 'Takizawa', ja: '滝沢市' },

    // MIYAGI
    [City.MiyagiSendai]: { en: 'Sendai', ja: '仙台市' },
    [City.MiyagiIshinomaki]: { en: 'Ishinomaki', ja: '石巻市' },
    [City.MiyagiShiogama]: { en: 'Shiogama', ja: '塩竈市' },
    [City.MiyagiKesennuma]: { en: 'Kesennuma', ja: '気仙沼市' },
    [City.MiyagiShiroishi]: { en: 'Shiroishi', ja: '白石市' },
    [City.MiyagiNatori]: { en: 'Natori', ja: '名取市' },
    [City.MiyagiKakuda]: { en: 'Kakuda', ja: '角田市' },
    [City.MiyagiTagajo]: { en: 'Tagajo', ja: '多賀城市' },
    [City.MiyagiIwanuma]: { en: 'Iwanuma', ja: '岩沼市' },
    [City.MiyagiTomiya]: { en: 'Tomiya', ja: '富谷市' },
    [City.MiyagiOsaki]: { en: 'Osaki', ja: '大崎市' },
    [City.MiyagiKurihara]: { en: 'Kurihara', ja: '栗原市' },
    [City.MiyagiHigashimatsushima]: { en: 'Higashimatsushima', ja: '東松島市' },
    [City.MiyagiWatari]: { en: 'Watari', ja: '亘理町' },

    // AKITA
    [City.AkitaAkita]: { en: 'Akita', ja: '秋田市' },
    [City.AkitaNoshiro]: { en: 'Noshiro', ja: '能代市' },
    [City.AkitaYokote]: { en: 'Yokote', ja: '横手市' },
    [City.AkitaOdate]: { en: 'Odate', ja: '大館市' },
    [City.AkitaOga]: { en: 'Oga', ja: '男鹿市' },
    [City.AkitaYuzawa]: { en: 'Yuzawa', ja: '湯沢市' },
    [City.AkitaKatagami]: { en: 'Katagami', ja: '潟上市' },
    [City.AkitaDaisen]: { en: 'Daisen', ja: '大仙市' },
    [City.AkitaKitaakita]: { en: 'Kitaakita', ja: '北秋田市' },
    [City.AkitaSemboku]: { en: 'Semboku', ja: '仙北市' },
    [City.AkitaNikaho]: { en: 'Nikaho', ja: 'にかほ市' },

    // YAMAGATA
    [City.YamagataYamagata]: { en: 'Yamagata', ja: '山形市' },
    [City.YamagataYonezawa]: { en: 'Yonezawa', ja: '米沢市' },
    [City.YamagataTsuruoka]: { en: 'Tsuruoka', ja: '鶴岡市' },
    [City.YamagataSakata]: { en: 'Sakata', ja: '酒田市' },
    [City.YamagataShinjo]: { en: 'Shinjo', ja: '新庄市' },
    [City.YamagataSagae]: { en: 'Sagae', ja: '寒河江市' },
    [City.YamagataKaminoyama]: { en: 'Kaminoyama', ja: '上山市' },
    [City.YamagataMurayama]: { en: 'Murayama', ja: '村山市' },
    [City.YamagataNagai]: { en: 'Nagai', ja: '長井市' },
    [City.YamagataTendo]: { en: 'Tendo', ja: '天童市' },
    [City.YamagataHigashine]: { en: 'Higashine', ja: '東根市' },
    [City.YamagataObanazawa]: { en: 'Obanazawa', ja: '尾花沢市' },
    [City.YamagataNanyo]: { en: 'Nanyo', ja: '南陽市' },

    // FUKUSHIMA
    [City.FukushimaFukushima]: { en: 'Fukushima', ja: '福島市' },
    [City.FukushimaAizuwakamatsu]: { en: 'Aizuwakamatsu', ja: '会津若松市' },
    [City.FukushimaKoriyama]: { en: 'Koriyama', ja: '郡山市' },
    [City.FukushimaIwaki]: { en: 'Iwaki', ja: 'いわき市' },
    [City.FukushimaShirakawa]: { en: 'Shirakawa', ja: '白河市' },
    [City.FukushimaSukagawa]: { en: 'Sukagawa', ja: '須賀川市' },
    [City.FukushimaKitakata]: { en: 'Kitakata', ja: '喜多方市' },
    [City.FukushimaSoma]: { en: 'Soma', ja: '相馬市' },
    [City.FukushimaDate]: { en: 'Date', ja: '伊達市' },
    [City.FukushimaMotomiya]: { en: 'Motomiya', ja: '本宮市' },
    [City.FukushimaNihonmatsu]: { en: 'Nihonmatsu', ja: '二本松市' },
    [City.FukushimaMinamisoma]: { en: 'Minamisoma', ja: '南相馬市' },
    [City.FukushimaTamura]: { en: 'Tamura', ja: '田村市' },

    // IBARAKI
    [City.IbarakiMito]: { en: 'Mito', ja: '水戸市' },
    [City.IbarakiHitachi]: { en: 'Hitachi', ja: '日立市' },
    [City.IbarakiTsuchiura]: { en: 'Tsuchiura', ja: '土浦市' },
    [City.IbarakiKoga]: { en: 'Koga', ja: '古河市' },
    [City.IbarakiIshioka]: { en: 'Ishioka', ja: '石岡市' },
    [City.IbarakiYuki]: { en: 'Yuki', ja: '結城市' },
    [City.IbarakiRyugasaki]: { en: 'Ryugasaki', ja: '龍ケ崎市' },
    [City.IbarakiShimotsuma]: { en: 'Shimotsuma', ja: '下妻市' },
    [City.IbarakiJoso]: { en: 'Joso', ja: '常総市' },
    [City.IbarakiHitachiota]: { en: 'Hitachiota', ja: '常陸太田市' },
    [City.IbarakiTakahagi]: { en: 'Takahagi', ja: '高萩市' },
    [City.IbarakiKitaibaraki]: { en: 'Kitaibaraki', ja: '北茨城市' },
    [City.IbarakiKasama]: { en: 'Kasama', ja: '笠間市' },
    [City.IbarakiToride]: { en: 'Toride', ja: '取手市' },
    [City.IbarakiUshiku]: { en: 'Ushiku', ja: '牛久市' },
    [City.IbarakiTsukuba]: { en: 'Tsukuba', ja: 'つくば市' },
    [City.IbarakiHitachinaka]: { en: 'Hitachinaka', ja: 'ひたちなか市' },
    [City.IbarakiKashima]: { en: 'Kashima', ja: '鹿嶋市' },
    [City.IbarakiItako]: { en: 'Itako', ja: '潮来市' },
    [City.IbarakiSakuragawa]: { en: 'Sakuragawa', ja: '桜川市' },
    [City.IbarakiKamisu]: { en: 'Kamisu', ja: '神栖市' },
    [City.IbarakiBando]: { en: 'Bando', ja: '坂東市' },
    [City.IbarakiInashiki]: { en: 'Inashiki', ja: '稲敷市' },
    [City.IbarakiKasumigaura]: { en: 'Kasumigaura', ja: 'かすみがうら市' },
    [City.IbarakiTsukubamirai]: { en: 'Tsukubamirai', ja: 'つくばみらい市' },
    [City.IbarakiOmitama]: { en: 'Omitama', ja: '小美玉市' },

    // TOCHIGI
    [City.TochigiUtsunomiya]: { en: 'Utsunomiya', ja: '宇都宮市' },
    [City.TochigiAshikaga]: { en: 'Ashikaga', ja: '足利市' },
    [City.TochigiTochigi]: { en: 'Tochigi', ja: '栃木市' },
    [City.TochigiSano]: { en: 'Sano', ja: '佐野市' },
    [City.TochigiKanuma]: { en: 'Kanuma', ja: '鹿沼市' },
    [City.TochigiNikko]: { en: 'Nikko', ja: '日光市' },
    [City.TochigiOyama]: { en: 'Oyama', ja: '小山市' },
    [City.TochigiMooka]: { en: 'Mooka', ja: '真岡市' },
    [City.TochigiOhtawara]: { en: 'Ohtawara', ja: '大田原市' },
    [City.TochigiYaita]: { en: 'Yaita', ja: '矢板市' },
    [City.TochigiNasushiobara]: { en: 'Nasushiobara', ja: '那須塩原市' },
    [City.TochigiSakura]: { en: 'Sakura', ja: 'さくら市' },
    [City.TochigiNasukarasuyama]: { en: 'Nasukarasuyama', ja: '那須烏山市' },
    [City.TochigiShimotsuke]: { en: 'Shimotsuke', ja: '下野市' },

    // GUNMA
    [City.GunmaMaebashi]: { en: 'Maebashi', ja: '前橋市' },
    [City.GunmaTakasaki]: { en: 'Takasaki', ja: '高崎市' },
    [City.GunmaKiryu]: { en: 'Kiryu', ja: '桐生市' },
    [City.GunmaIsesaki]: { en: 'Isesaki', ja: '伊勢崎市' },
    [City.GunmaOta]: { en: 'Ota', ja: '太田市' },
    [City.GunmaNumata]: { en: 'Numata', ja: '沼田市' },
    [City.GunmaTatebayashi]: { en: 'Tatebayashi', ja: '館林市' },
    [City.GunmaShibukawa]: { en: 'Shibukawa', ja: '渋川市' },
    [City.GunmaFujioka]: { en: 'Fujioka', ja: '藤岡市' },
    [City.GunmaTomioka]: { en: 'Tomioka', ja: '富岡市' },
    [City.GunmaAnnaka]: { en: 'Annaka', ja: '安中市' },
    [City.GunmaMidori]: { en: 'Midori', ja: 'みどり市' },

    // SAITAMA
    [City.SaitamaSaitama]: { en: 'Saitama', ja: 'さいたま市' },
    [City.SaitamaKawaguchi]: { en: 'Kawaguchi', ja: '川口市' },
    [City.SaitamaKawagoe]: { en: 'Kawagoe', ja: '川越市' },
    [City.SaitamaKumagaya]: { en: 'Kumagaya', ja: '熊谷市' },
    [City.SaitamaGyoda]: { en: 'Gyoda', ja: '行田市' },
    [City.SaitamaChichibu]: { en: 'Chichibu', ja: '秩父市' },
    [City.SaitamaTokorozawa]: { en: 'Tokorozawa', ja: '所沢市' },
    [City.SaitamaHanno]: { en: 'Hanno', ja: '飯能市' },
    [City.SaitamaKazo]: { en: 'Kazo', ja: '加須市' },
    [City.SaitamaHonjo]: { en: 'Honjo', ja: '本庄市' },
    [City.SaitamaHigashimatsuyama]: { en: 'Higashimatsuyama', ja: '東松山市' },
    [City.SaitamaKasukabe]: { en: 'Kasukabe', ja: '春日部市' },
    [City.SaitamaSayama]: { en: 'Sayama', ja: '狭山市' },
    [City.SaitamaHanyu]: { en: 'Hanyu', ja: '羽生市' },
    [City.SaitamaKonosu]: { en: 'Konosu', ja: '鴻巣市' },
    [City.SaitamaFukaya]: { en: 'Fukaya', ja: '深谷市' },
    [City.SaitamaAgeo]: { en: 'Ageo', ja: '上尾市' },
    [City.SaitamaKoshigaya]: { en: 'Koshigaya', ja: '越谷市' },
    [City.SaitamaWarabi]: { en: 'Warabi', ja: '蕨市' },
    [City.SaitamaToda]: { en: 'Toda', ja: '戸田市' },
    [City.SaitamaIruma]: { en: 'Iruma', ja: '入間市' },
    [City.SaitamaAsaka]: { en: 'Asaka', ja: '朝霞市' },
    [City.SaitamaShiki]: { en: 'Shiki', ja: '志木市' },
    [City.SaitamaWako]: { en: 'Wako', ja: '和光市' },
    [City.SaitamaNiiza]: { en: 'Niiza', ja: '新座市' },
    [City.SaitamaOkegawa]: { en: 'Okegawa', ja: '桶川市' },
    [City.SaitamaKuki]: { en: 'Kuki', ja: '久喜市' },
    [City.SaitamaKitamoto]: { en: 'Kitamoto', ja: '北本市' },
    [City.SaitamaYashio]: { en: 'Yashio', ja: '八潮市' },
    [City.SaitamaFujimi]: { en: 'Fujimi', ja: '富士見市' },
    [City.SaitamaMisato]: { en: 'Misato', ja: '三郷市' },
    [City.SaitamaHasuda]: { en: 'Hasuda', ja: '蓮田市' },
    [City.SaitamaSakado]: { en: 'Sakado', ja: '坂戸市' },
    [City.SaitamaSatte]: { en: 'Satte', ja: '幸手市' },
    [City.SaitamaTsurugashima]: { en: 'Tsurugashima', ja: '鶴ヶ島市' },
    [City.SaitamaHidaka]: { en: 'Hidaka', ja: '日高市' },
    [City.SaitamaYoshikawa]: { en: 'Yoshikawa', ja: '吉川市' },
    [City.SaitamaFujimino]: { en: 'Fujimino', ja: 'ふじみ野市' },
    [City.SaitamaSouka]: { en: 'Souka', ja: '草加市' },

    // CHIBA
    [City.ChibaChiba]: { en: 'Chiba', ja: '千葉市' },
    [City.ChibaChoshi]: { en: 'Choshi', ja: '銚子市' },
    [City.ChibaIchikawa]: { en: 'Ichikawa', ja: '市川市' },
    [City.ChibaFunabashi]: { en: 'Funabashi', ja: '船橋市' },
    [City.ChibaTateyama]: { en: 'Tateyama', ja: '館山市' },
    [City.ChibaKisarazu]: { en: 'Kisarazu', ja: '木更津市' },
    [City.ChibaMatsudo]: { en: 'Matsudo', ja: '松戸市' },
    [City.ChibaNoda]: { en: 'Noda', ja: '野田市' },
    [City.ChibaMobara]: { en: 'Mobara', ja: '茂原市' },
    [City.ChibaNarita]: { en: 'Narita', ja: '成田市' },
    [City.ChibaSakura]: { en: 'Sakura', ja: '佐倉市' },
    [City.ChibaTogane]: { en: 'Togane', ja: '東金市' },
    [City.ChibaAsahi]: { en: 'Asahi', ja: '旭市' },
    [City.ChibaNarashino]: { en: 'Narashino', ja: '習志野市' },
    [City.ChibaKashiwa]: { en: 'Kashiwa', ja: '柏市' },
    [City.ChibaKatsuura]: { en: 'Katsuura', ja: '勝浦市' },
    [City.ChibaIchihara]: { en: 'Ichihara', ja: '市原市' },
    [City.ChibaNagareyama]: { en: 'Nagareyama', ja: '流山市' },
    [City.ChibaYachiyo]: { en: 'Yachiyo', ja: '八千代市' },
    [City.ChibaAbiko]: { en: 'Abiko', ja: '我孫子市' },
    [City.ChibaKamogawa]: { en: 'Kamogawa', ja: '鴨川市' },
    [City.ChibaKamagaya]: { en: 'Kamagaya', ja: '鎌ケ谷市' },
    [City.ChibaKimitsu]: { en: 'Kimitsu', ja: '君津市' },
    [City.ChibaFuttsu]: { en: 'Futtsu', ja: '富津市' },
    [City.ChibaUrayasu]: { en: 'Urayasu', ja: '浦安市' },
    [City.ChibaYotsukaido]: { en: 'Yotsukaido', ja: '四街道市' },
    [City.ChibaSodegaura]: { en: 'Sodegaura', ja: '袖ケ浦市' },
    [City.ChibaYachimata]: { en: 'Yachimata', ja: '八街市' },
    [City.ChibaInzai]: { en: 'Inzai', ja: '印西市' },
    [City.ChibaShiroi]: { en: 'Shiroi', ja: '白井市' },
    [City.ChibaTomisato]: { en: 'Tomisato', ja: '富里市' },
    [City.ChibaMinamiboso]: { en: 'Minamiboso', ja: '南房総市' },
    [City.ChibaSosa]: { en: 'Sosa', ja: '匝瑳市' },
    [City.ChibaKatori]: { en: 'Katori', ja: '香取市' },
    [City.ChibaSanmu]: { en: 'Sanmu', ja: '山武市' },
    [City.ChibaIsumi]: { en: 'Isumi', ja: 'いすみ市' },
    [City.ChibaOamishirasato]: { en: 'Oamishirasato', ja: '大網白里市' },

    // TOKYO (23 Wards)
    [City.TokyoChiyoda]: { en: 'Chiyoda', ja: '千代田区' },
    [City.TokyoChuo]: { en: 'Chuo', ja: '中央区' },
    [City.TokyoMinato]: { en: 'Minato', ja: '港区' },
    [City.TokyoShinjuku]: { en: 'Shinjuku', ja: '新宿区' },
    [City.TokyoBunkyo]: { en: 'Bunkyo', ja: '文京区' },
    [City.TokyoTaito]: { en: 'Taito', ja: '台東区' },
    [City.TokyoSumida]: { en: 'Sumida', ja: '墨田区' },
    [City.TokyoKoto]: { en: 'Koto', ja: '江東区' },
    [City.TokyoShinagawa]: { en: 'Shinagawa', ja: '品川区' },
    [City.TokyoMeguro]: { en: 'Meguro', ja: '目黒区' },
    [City.TokyoOta]: { en: 'Ota', ja: '大田区' },
    [City.TokyoSetagaya]: { en: 'Setagaya', ja: '世田谷区' },
    [City.TokyoShibuya]: { en: 'Shibuya', ja: '渋谷区' },
    [City.TokyoNakano]: { en: 'Nakano', ja: '中野区' },
    [City.TokyoSuginami]: { en: 'Suginami', ja: '杉並区' },
    [City.TokyoToshima]: { en: 'Toshima', ja: '豊島区' },
    [City.TokyoKita]: { en: 'Kita', ja: '北区' },
    [City.TokyoArakawa]: { en: 'Arakawa', ja: '荒川区' },
    [City.TokyoItabashi]: { en: 'Itabashi', ja: '板橋区' },
    [City.TokyoNerima]: { en: 'Nerima', ja: '練馬区' },
    [City.TokyoAdachi]: { en: 'Adachi', ja: '足立区' },
    [City.TokyoKatsushika]: { en: 'Katsushika', ja: '葛飾区' },
    [City.TokyoEdogawa]: { en: 'Edogawa', ja: '江戸川区' },

    // TOKYO (Cities)
    [City.TokyoHachioji]: { en: 'Hachioji', ja: '八王子市' },
    [City.TokyoTachikawa]: { en: 'Tachikawa', ja: '立川市' },
    [City.TokyoMusashino]: { en: 'Musashino', ja: '武蔵野市' },
    [City.TokyoMitaka]: { en: 'Mitaka', ja: '三鷹市' },
    [City.TokyoOme]: { en: 'Ome', ja: '青梅市' },
    [City.TokyoFuchu]: { en: 'Fuchu', ja: '府中市' },
    [City.TokyoAkishima]: { en: 'Akishima', ja: '昭島市' },
    [City.TokyoChofu]: { en: 'Chofu', ja: '調布市' },
    [City.TokyoMachida]: { en: 'Machida', ja: '町田市' },
    [City.TokyoKoganei]: { en: 'Koganei', ja: '小金井市' },
    [City.TokyoKodaira]: { en: 'Kodaira', ja: '小平市' },
    [City.TokyoHino]: { en: 'Hino', ja: '日野市' },
    [City.TokyoHigashimurayama]: { en: 'Higashimurayama', ja: '東村山市' },
    [City.TokyoKokubunji]: { en: 'Kokubunji', ja: '国分寺市' },
    [City.TokyoKunitachi]: { en: 'Kunitachi', ja: '国立市' },
    [City.TokyoFussa]: { en: 'Fussa', ja: '福生市' },
    [City.TokyoKomae]: { en: 'Komae', ja: '狛江市' },
    [City.TokyoHigashiyamato]: { en: 'Higashiyamato', ja: '東大和市' },
    [City.TokyoKiyose]: { en: 'Kiyose', ja: '清瀬市' },
    [City.TokyoHigashikurume]: { en: 'Higashikurume', ja: '東久留米市' },
    [City.TokyoMusashimurayama]: { en: 'Musashimurayama', ja: '武蔵村山市' },
    [City.TokyoTama]: { en: 'Tama', ja: '多摩市' },
    [City.TokyoInagi]: { en: 'Inagi', ja: '稲城市' },
    [City.TokyoHamura]: { en: 'Hamura', ja: '羽村市' },
    [City.TokyoAkiruno]: { en: 'Akiruno', ja: 'あきる野市' },
    [City.TokyoNishitokyo]: { en: 'Nishitokyo', ja: '西東京市' },

    // KANAGAWA
    [City.KanagawaYokohama]: { en: 'Yokohama', ja: '横浜市' },
    [City.KanagawaKawasaki]: { en: 'Kawasaki', ja: '川崎市' },
    [City.KanagawaSagamihara]: { en: 'Sagamihara', ja: '相模原市' },
    [City.KanagawaYokosuka]: { en: 'Yokosuka', ja: '横須賀市' },
    [City.KanagawaFujisawa]: { en: 'Fujisawa', ja: '藤沢市' },
    [City.KanagawaHiratsuka]: { en: 'Hiratsuka', ja: '平塚市' },
    [City.KanagawaKamakura]: { en: 'Kamakura', ja: '鎌倉市' },
    [City.KanagawaChigasaki]: { en: 'Chigasaki', ja: '茅ヶ崎市' },
    [City.KanagawaAtsugi]: { en: 'Atsugi', ja: '厚木市' },
    [City.KanagawaYamato]: { en: 'Yamato', ja: '大和市' },
    [City.KanagawaOdawara]: { en: 'Odawara', ja: '小田原市' },
    [City.KanagawaIsehara]: { en: 'Isehara', ja: '伊勢原市' },
    [City.KanagawaEbina]: { en: 'Ebina', ja: '海老名市' },
    [City.KanagawaZama]: { en: 'Zama', ja: '座間市' },
    [City.KanagawaZushi]: { en: 'Zushi', ja: '逗子市' },
    [City.KanagawaMinamiashigara]: { en: 'Minamiashigara', ja: '南足柄市' },
    [City.KanagawaHadano]: { en: 'Hadano', ja: '秦野市' },

    // NIIGATA
    [City.NiigataNiigata]: { en: 'Niigata', ja: '新潟市' },
    [City.NiigataJoetsu]: { en: 'Joetsu', ja: '上越市' },
    [City.NiigataKashiwazaki]: { en: 'Kashiwazaki', ja: '柏崎市' },
    [City.NiigataShibata]: { en: 'Shibata', ja: '新発田市' },
    [City.NiigataNagaoka]: { en: 'Nagaoka', ja: '長岡市' },
    [City.NiigataSanjo]: { en: 'Sanjo', ja: '三条市' },
    [City.NiigataOjiya]: { en: 'Ojiya', ja: '小千谷市' },
    [City.NiigataKamo]: { en: 'Kamo', ja: '加茂市' },
    [City.NiigataTokamachi]: { en: 'Tokamachi', ja: '十日町市' },
    [City.NiigataMitsuke]: { en: 'Mitsuke', ja: '見附市' },
    [City.NiigataMurakami]: { en: 'Murakami', ja: '村上市' },
    [City.NiigataItoigawa]: { en: 'Itoigawa', ja: '糸魚川市' },
    [City.NiigataSado]: { en: 'Sado', ja: '佐渡市' },
    [City.NiigataUonuma]: { en: 'Uonuma', ja: '魚沼市' },
    [City.NiigataMinamiuonuma]: { en: 'Minamiuonuma', ja: '南魚沼市' },
    [City.NiigataTsubame]: { en: 'Tsubame', ja: '燕市' },
    [City.NiigataMyoko]: { en: 'Myoko', ja: '妙高市' },
    [City.NiigataGosen]: { en: 'Gosen', ja: '五泉市' },
    [City.NiigataAgano]: { en: 'Agano', ja: '阿賀野市' },
    [City.NiigataTainai]: { en: 'Tainai', ja: '胎内市' },

    // TOYAMA
    [City.ToyamaToyama]: { en: 'Toyama', ja: '富山市' },
    [City.ToyamaTakaoka]: { en: 'Takaoka', ja: '高岡市' },
    [City.ToyamaUozu]: { en: 'Uozu', ja: '魚津市' },
    [City.ToyamaHimi]: { en: 'Himi', ja: '氷見市' },
    [City.ToyamaNamerikawa]: { en: 'Namerikawa', ja: '滑川市' },
    [City.ToyamaKurobe]: { en: 'Kurobe', ja: '黒部市' },
    [City.ToyamaTonami]: { en: 'Tonami', ja: '砺波市' },
    [City.ToyamaOyabe]: { en: 'Oyabe', ja: '小矢部市' },
    [City.ToyamaNanto]: { en: 'Nanto', ja: '南砺市' },
    [City.ToyamaImizu]: { en: 'Imizu', ja: '射水市' },

    // ISHIKAWA
    [City.IshikawaKanazawa]: { en: 'Kanazawa', ja: '金沢市' },
    [City.IshikawaNanao]: { en: 'Nanao', ja: '七尾市' },
    [City.IshikawaKomatsu]: { en: 'Komatsu', ja: '小松市' },
    [City.IshikawaWajima]: { en: 'Wajima', ja: '輪島市' },
    [City.IshikawaSuzu]: { en: 'Suzu', ja: '珠洲市' },
    [City.IshikawaKaga]: { en: 'Kaga', ja: '加賀市' },
    [City.IshikawaHakui]: { en: 'Hakui', ja: '羽咋市' },
    [City.IshikawaKahoku]: { en: 'Kahoku', ja: 'かほく市' },
    [City.IshikawaHakusan]: { en: 'Hakusan', ja: '白山市' },
    [City.IshikawaNomi]: { en: 'Nomi', ja: '能美市' },
    [City.IshikawaNoto]: { en: 'Noto', ja: '野々市市' },

    // FUKUI
    [City.FukuiFukui]: { en: 'Fukui', ja: '福井市' },
    [City.FukuiTsuruga]: { en: 'Tsuruga', ja: '敦賀市' },
    [City.FukuiObama]: { en: 'Obama', ja: '小浜市' },
    [City.FukuiOno]: { en: 'Ono', ja: '大野市' },
    [City.FukuiKatsuyama]: { en: 'Katsuyama', ja: '勝山市' },
    [City.FukuiSabae]: { en: 'Sabae', ja: '鯖江市' },
    [City.FukuiAwara]: { en: 'Awara', ja: 'あわら市' },
    [City.FukuiEchizen]: { en: 'Echizen', ja: '越前市' },
    [City.FukuiSakai]: { en: 'Sakai', ja: '坂井市' },

    // YAMANASHI
    [City.YamanashiKofu]: { en: 'Kofu', ja: '甲府市' },
    [City.YamanashiFujiyoshida]: { en: 'Fujiyoshida', ja: '富士吉田市' },
    [City.YamanashiTsuru]: { en: 'Tsuru', ja: '都留市' },
    [City.YamanashiYamanashi]: { en: 'Yamanashi', ja: '山梨市' },
    [City.YamanashiOtsuki]: { en: 'Otsuki', ja: '大月市' },
    [City.YamanashiNirasaki]: { en: 'Nirasaki', ja: '韮崎市' },
    [City.YamanashiMinamiArupusu]: { en: 'Minami Arupusu', ja: '南アルプス市' },
    [City.YamanashiHokuto]: { en: 'Hokuto', ja: '北杜市' },
    [City.YamanashiKai]: { en: 'Kai', ja: '甲斐市' },
    [City.YamanashiFuefuki]: { en: 'Fuefuki', ja: '笛吹市' },
    [City.YamanashiUenohara]: { en: 'Uenohara', ja: '上野原市' },
    [City.YamanashiKoshu]: { en: 'Koshu', ja: '甲州市' },
    [City.YamanashiChuo]: { en: 'Chuo', ja: '中央市' },

    // NAGANO
    [City.NaganoNagano]: { en: 'Nagano', ja: '長野市' },
    [City.NaganoMatsumoto]: { en: 'Matsumoto', ja: '松本市' },
    [City.NaganoUeda]: { en: 'Ueda', ja: '上田市' },
    [City.NaganoOkaya]: { en: 'Okaya', ja: '岡谷市' },
    [City.NaganoIida]: { en: 'Iida', ja: '飯田市' },
    [City.NaganoSuwa]: { en: 'Suwa', ja: '諏訪市' },
    [City.NaganoKomagane]: { en: 'Komagane', ja: '駒ヶ根市' },
    [City.NaganoIna]: { en: 'Ina', ja: '伊那市' },
    [City.NaganoKomoro]: { en: 'Komoro', ja: '小諸市' },
    [City.NaganoIiyama]: { en: 'Iiyama', ja: '飯山市' },
    [City.NaganoSaku]: { en: 'Saku', ja: '佐久市' },
    [City.NaganoChino]: { en: 'Chino', ja: '茅野市' },
    [City.NaganoOmachi]: { en: 'Omachi', ja: '大町市' },
    [City.NaganoAzumino]: { en: 'Azumino', ja: '安曇野市' },
    [City.NaganoShiojiri]: { en: 'Shiojiri', ja: '塩尻市' },
    [City.NaganoTomi]: { en: 'Tomi', ja: '東御市' },
    [City.NaganoNakano]: { en: 'Nakano', ja: '中野市' },
    [City.NaganoChikuma]: { en: 'Chikuma', ja: '千曲市' },

    // GIFU
    [City.GifuGifu]: { en: 'Gifu', ja: '岐阜市' },
    [City.GifuOgaki]: { en: 'Ogaki', ja: '大垣市' },
    [City.GifuTakayama]: { en: 'Takayama', ja: '高山市' },
    [City.GifuTajimi]: { en: 'Tajimi', ja: '多治見市' },
    [City.GifuSeki]: { en: 'Seki', ja: '関市' },
    [City.GifuNakatsugawa]: { en: 'Nakatsugawa', ja: '中津川市' },
    [City.GifuMino]: { en: 'Mino', ja: '美濃市' },
    [City.GifuMizunami]: { en: 'Mizunami', ja: '瑞浪市' },
    [City.GifuHashima]: { en: 'Hashima', ja: '羽島市' },
    [City.GifuEna]: { en: 'Ena', ja: '恵那市' },
    [City.GifuMinokamo]: { en: 'Minokamo', ja: '美濃加茂市' },
    [City.GifuToki]: { en: 'Toki', ja: '土岐市' },
    [City.GifuKakamigahara]: { en: 'Kakamigahara', ja: '各務原市' },
    [City.GifuKani]: { en: 'Kani', ja: '可児市' },
    [City.GifuYamagata]: { en: 'Yamagata', ja: '山県市' },
    [City.GifuMizuho]: { en: 'Mizuho', ja: '瑞穂市' },
    [City.GifuHida]: { en: 'Hida', ja: '飛騨市' },
    [City.GifuMotosu]: { en: 'Motosu', ja: '本巣市' },
    [City.GifuGero]: { en: 'Gero', ja: '下呂市' },
    [City.GifuKaizu]: { en: 'Kaizu', ja: '海津市' },

    // SHIZUOKA
    [City.ShizuokaShizuoka]: { en: 'Shizuoka', ja: '静岡市' },
    [City.ShizuokaHamamatsu]: { en: 'Hamamatsu', ja: '浜松市' },
    [City.ShizuokaNumazu]: { en: 'Numazu', ja: '沼津市' },
    [City.ShizuokaAtami]: { en: 'Atami', ja: '熱海市' },
    [City.ShizuokaMishima]: { en: 'Mishima', ja: '三島市' },
    [City.ShizuokaFujinomiya]: { en: 'Fujinomiya', ja: '富士宮市' },
    [City.ShizuokaIto]: { en: 'Ito', ja: '伊東市' },
    [City.ShizuokaShimada]: { en: 'Shimada', ja: '島田市' },
    [City.ShizuokaFuji]: { en: 'Fuji', ja: '富士市' },
    [City.ShizuokaYaizu]: { en: 'Yaizu', ja: '焼津市' },
    [City.ShizuokaKakegawa]: { en: 'Kakegawa', ja: '掛川市' },
    [City.ShizuokaFujieda]: { en: 'Fujieda', ja: '藤枝市' },
    [City.ShizuokaGotemba]: { en: 'Gotemba', ja: '御殿場市' },
    [City.ShizuokaShimoda]: { en: 'Shimoda', ja: '下田市' },
    [City.ShizuokaSusono]: { en: 'Susono', ja: '裾野市' },
    [City.ShizuokaKosai]: { en: 'Kosai', ja: '湖西市' },
    [City.ShizuokaIzu]: { en: 'Izu', ja: '伊豆市' },
    [City.ShizuokaOmaezaki]: { en: 'Omaezaki', ja: '御前崎市' },
    [City.ShizuokaKikugawa]: { en: 'Kikugawa', ja: '菊川市' },
    [City.ShizuokaIzunokuni]: { en: 'Izunokuni', ja: '伊豆の国市' },
    [City.ShizuokaMakinohara]: { en: 'Makinohara', ja: '牧之原市' },

    // AICHI
    [City.AichiNagoya]: { en: 'Nagoya', ja: '名古屋市' },
    [City.AichiToyohashi]: { en: 'Toyohashi', ja: '豊橋市' },
    [City.AichiOkazaki]: { en: 'Okazaki', ja: '岡崎市' },
    [City.AichiIchinomiya]: { en: 'Ichinomiya', ja: '一宮市' },
    [City.AichiSeto]: { en: 'Seto', ja: '瀬戸市' },
    [City.AichiHanda]: { en: 'Handa', ja: '半田市' },
    [City.AichiKasugai]: { en: 'Kasugai', ja: '春日井市' },
    [City.AichiToyokawa]: { en: 'Toyokawa', ja: '豊川市' },
    [City.AichiTsushima]: { en: 'Tsushima', ja: '津島市' },
    [City.AichiHekinan]: { en: 'Hekinan', ja: '碧南市' },
    [City.AichiKariya]: { en: 'Kariya', ja: '刈谷市' },
    [City.AichiToyota]: { en: 'Toyota', ja: '豊田市' },
    [City.AichiAnjo]: { en: 'Anjo', ja: '安城市' },
    [City.AichiNishio]: { en: 'Nishio', ja: '西尾市' },
    [City.AichiGamagori]: { en: 'Gamagori', ja: '蒲郡市' },
    [City.AichiInuyama]: { en: 'Inuyama', ja: '犬山市' },
    [City.AichiTokoname]: { en: 'Tokoname', ja: '常滑市' },
    [City.AichiKonan]: { en: 'Konan', ja: '江南市' },
    [City.AichiKomaki]: { en: 'Komaki', ja: '小牧市' },
    [City.AichiInazawa]: { en: 'Inazawa', ja: '稲沢市' },
    [City.AichiOwariasahi]: { en: 'Owariasahi', ja: '尾張旭市' },
    [City.AichiTakahama]: { en: 'Takahama', ja: '高浜市' },
    [City.AichiIwakura]: { en: 'Iwakura', ja: '岩倉市' },
    [City.AichiToyoake]: { en: 'Toyoake', ja: '豊明市' },
    [City.AichiNisshin]: { en: 'Nisshin', ja: '日進市' },
    [City.AichiTahara]: { en: 'Tahara', ja: '田原市' },
    [City.AichiAisai]: { en: 'Aisai', ja: '愛西市' },
    [City.AichiKiyosu]: { en: 'Kiyosu', ja: '清須市' },
    [City.AichiKitanagoya]: { en: 'Kitanagoya', ja: '北名古屋市' },
    [City.AichiYatomi]: { en: 'Yatomi', ja: '弥富市' },
    [City.AichiMiyoshi]: { en: 'Miyoshi', ja: 'みよし市' },
    [City.AichiAma]: { en: 'Ama', ja: 'あま市' },
    [City.AichiNagakute]: { en: 'Nagakute', ja: '長久手市' },

    // MIE
    [City.MieTsu]: { en: 'Tsu', ja: '津市' },
    [City.MieYokkaichi]: { en: 'Yokkaichi', ja: '四日市市' },
    [City.MieIse]: { en: 'Ise', ja: '伊勢市' },
    [City.MieMatsusaka]: { en: 'Matsusaka', ja: '松阪市' },
    [City.MieKuwana]: { en: 'Kuwana', ja: '桑名市' },
    [City.MieSuzuka]: { en: 'Suzuka', ja: '鈴鹿市' },
    [City.MieNabari]: { en: 'Nabari', ja: '名張市' },
    [City.MieOwase]: { en: 'Owase', ja: '尾鷲市' },
    [City.MieKameyama]: { en: 'Kameyama', ja: '亀山市' },
    [City.MieToba]: { en: 'Toba', ja: '鳥羽市' },
    [City.MieKumano]: { en: 'Kumano', ja: '熊野市' },
    [City.MieInabe]: { en: 'Inabe', ja: 'いなべ市' },
    [City.MieShima]: { en: 'Shima', ja: '志摩市' },
    [City.MieIga]: { en: 'Iga', ja: '伊賀市' },

    // SHIGA
    [City.ShigaOtsu]: { en: 'Otsu', ja: '大津市' },
    [City.ShigaHikone]: { en: 'Hikone', ja: '彦根市' },
    [City.ShigaNagahama]: { en: 'Nagahama', ja: '長浜市' },
    [City.ShigaOmihachiman]: { en: 'Omihachiman', ja: '近江八幡市' },
    [City.ShigaKusatsu]: { en: 'Kusatsu', ja: '草津市' },
    [City.ShigaMoriyama]: { en: 'Moriyama', ja: '守山市' },
    [City.ShigaRitto]: { en: 'Ritto', ja: '栗東市' },
    [City.ShigaKoka]: { en: 'Koka', ja: '甲賀市' },
    [City.ShigaYasu]: { en: 'Yasu', ja: '野洲市' },
    [City.ShigaKonan]: { en: 'Konan', ja: '湖南市' },
    [City.ShigaTakashima]: { en: 'Takashima', ja: '高島市' },
    [City.ShigaHigashiomi]: { en: 'Higashiomi', ja: '東近江市' },
    [City.ShigaMaibara]: { en: 'Maibara', ja: '米原市' },

    // KYOTO
    [City.KyotoKyoto]: { en: 'Kyoto', ja: '京都市' },
    [City.KyotoFukuchiyama]: { en: 'Fukuchiyama', ja: '福知山市' },
    [City.KyotoMaizuru]: { en: 'Maizuru', ja: '舞鶴市' },
    [City.KyotoAyabe]: { en: 'Ayabe', ja: '綾部市' },
    [City.KyotoUji]: { en: 'Uji', ja: '宇治市' },
    [City.KyotoMiyazu]: { en: 'Miyazu', ja: '宮津市' },
    [City.KyotoKameoka]: { en: 'Kameoka', ja: '亀岡市' },
    [City.KyotoJoyo]: { en: 'Joyo', ja: '城陽市' },
    [City.KyotoMuko]: { en: 'Muko', ja: '向日市' },
    [City.KyotoNagaokakyo]: { en: 'Nagaokakyo', ja: '長岡京市' },
    [City.KyotoYawata]: { en: 'Yawata', ja: '八幡市' },
    [City.KyotoKyotanabe]: { en: 'Kyotanabe', ja: '京田辺市' },
    [City.KyotoKyotango]: { en: 'Kyotango', ja: '京丹後市' },
    [City.KyotoNantan]: { en: 'Nantan', ja: '南丹市' },
    [City.KyotoKizugawa]: { en: 'Kizugawa', ja: '木津川市' },

    // OSAKA
    [City.OsakaOsaka]: { en: 'Osaka', ja: '大阪市' },
    [City.OsakaSakai]: { en: 'Sakai', ja: '堺市' },
    [City.OsakaToyonaka]: { en: 'Toyonaka', ja: '豊中市' },
    [City.OsakaIkeda]: { en: 'Ikeda', ja: '池田市' },
    [City.OsakaSuita]: { en: 'Suita', ja: '吹田市' },
    [City.OsakaTakatsuki]: { en: 'Takatsuki', ja: '高槻市' },
    [City.OsakaKaizuka]: { en: 'Kaizuka', ja: '貝塚市' },
    [City.OsakaMoriguchi]: { en: 'Moriguchi', ja: '守口市' },
    [City.OsakaHirakata]: { en: 'Hirakata', ja: '枚方市' },
    [City.OsakaIbaraki]: { en: 'Ibaraki', ja: '茨木市' },
    [City.OsakaYao]: { en: 'Yao', ja: '八尾市' },
    [City.OsakaIzumisano]: { en: 'Izumisano', ja: '泉佐野市' },
    [City.OsakaTondabayashi]: { en: 'Tondabayashi', ja: '富田林市' },
    [City.OsakaNeyagawa]: { en: 'Neyagawa', ja: '寝屋川市' },
    [City.OsakaKawachinagano]: { en: 'Kawachinagano', ja: '河内長野市' },
    [City.OsakaMatsubara]: { en: 'Matsubara', ja: '松原市' },
    [City.OsakaDaito]: { en: 'Daito', ja: '大東市' },
    [City.OsakaIzumi]: { en: 'Izumi', ja: '和泉市' },
    [City.OsakaMinoh]: { en: 'Minoh', ja: '箕面市' },
    [City.OsakaKashiwara]: { en: 'Kashiwara', ja: '柏原市' },
    [City.OsakaHabikino]: { en: 'Habikino', ja: '羽曳野市' },
    [City.OsakaKadoma]: { en: 'Kadoma', ja: '門真市' },
    [City.OsakaSettsu]: { en: 'Settsu', ja: '摂津市' },
    [City.OsakaTakaishi]: { en: 'Takaishi', ja: '高石市' },
    [City.OsakaFujiidera]: { en: 'Fujiidera', ja: '藤井寺市' },
    [City.OsakaHigashiosaka]: { en: 'Higashiosaka', ja: '東大阪市' },
    [City.OsakaSennan]: { en: 'Sennan', ja: '泉南市' },
    [City.OsakaShijonawate]: { en: 'Shijonawate', ja: '四條畷市' },
    [City.OsakaKatano]: { en: 'Katano', ja: '交野市' },
    [City.OsakaOsakasayama]: { en: 'Osakasayama', ja: '大阪狭山市' },
    [City.OsakaHannan]: { en: 'Hannan', ja: '阪南市' },

    // HYOGO
    [City.HyogoKobe]: { en: 'Kobe', ja: '神戸市' },
    [City.HyogoHimeji]: { en: 'Himeji', ja: '姫路市' },
    [City.HyogoAmagasaki]: { en: 'Amagasaki', ja: '尼崎市' },
    [City.HyogoAkashi]: { en: 'Akashi', ja: '明石市' },
    [City.HyogoNishinomiya]: { en: 'Nishinomiya', ja: '西宮市' },
    [City.HyogoSumoto]: { en: 'Sumoto', ja: '洲本市' },
    [City.HyogoAshiya]: { en: 'Ashiya', ja: '芦屋市' },
    [City.HyogoItami]: { en: 'Itami', ja: '伊丹市' },
    [City.HyogoAioi]: { en: 'Aioi', ja: '相生市' },
    [City.HyogoToyooka]: { en: 'Toyooka', ja: '豊岡市' },
    [City.HyogoKakogawa]: { en: 'Kakogawa', ja: '加古川市' },
    [City.HyogoAko]: { en: 'Ako', ja: '赤穂市' },
    [City.HyogoNishiwaki]: { en: 'Nishiwaki', ja: '西脇市' },
    [City.HyogoTakarazuka]: { en: 'Takarazuka', ja: '宝塚市' },
    [City.HyogoMiki]: { en: 'Miki', ja: '三木市' },
    [City.HyogoTakasago]: { en: 'Takasago', ja: '高砂市' },
    [City.HyogoKawanishi]: { en: 'Kawanishi', ja: '川西市' },
    [City.HyogoOno]: { en: 'Ono', ja: '小野市' },
    [City.HyogoSanda]: { en: 'Sanda', ja: '三田市' },
    [City.HyogoKasai]: { en: 'Kasai', ja: '加西市' },
    [City.HyogoSasayama]: { en: 'Sasayama', ja: '丹波篠山市' },
    [City.HyogoYabu]: { en: 'Yabu', ja: '養父市' },
    [City.HyogoTamba]: { en: 'Tamba', ja: '丹波市' },
    [City.HyogoMinami]: { en: 'Minami', ja: '南あわじ市' },
    [City.HyogoAwaji]: { en: 'Awaji', ja: '淡路市' },
    [City.HyogoShiso]: { en: 'Shiso', ja: '宍粟市' },
    [City.HyogoKato]: { en: 'Kato', ja: '加東市' },
    [City.HyogoTatsuno]: { en: 'Tatsuno', ja: 'たつの市' },

    // NARA
    [City.NaraNara]: { en: 'Nara', ja: '奈良市' },
    [City.NaraYamatokoriyama]: { en: 'Yamatokoriyama', ja: '大和郡山市' },
    [City.NaraYamatotakada]: { en: 'Yamatotakada', ja: '大和高田市' },
    [City.NaraKashihara]: { en: 'Kashihara', ja: '橿原市' },
    [City.NaraSakurai]: { en: 'Sakurai', ja: '桜井市' },
    [City.NaraGojo]: { en: 'Gojo', ja: '五條市' },
    [City.NaraGose]: { en: 'Gose', ja: '御所市' },
    [City.NaraIkoma]: { en: 'Ikoma', ja: '生駒市' },
    [City.NaraKashiba]: { en: 'Kashiba', ja: '香芝市' },
    [City.NaraKatsuragi]: { en: 'Katsuragi', ja: '葛城市' },
    [City.NaraUda]: { en: 'Uda', ja: '宇陀市' },
    [City.NaraTenri]: { en: 'Tenri', ja: '天理市' },

    // WAKAYAMA
    [City.WakayamaWakayama]: { en: 'Wakayama', ja: '和歌山市' },
    [City.WakayamaKainan]: { en: 'Kainan', ja: '海南市' },
    [City.WakayamaHashimoto]: { en: 'Hashimoto', ja: '橋本市' },
    [City.WakayamaArida]: { en: 'Arida', ja: '有田市' },
    [City.WakayamaGobo]: { en: 'Gobo', ja: '御坊市' },
    [City.WakayamaTanabe]: { en: 'Tanabe', ja: '田辺市' },
    [City.WakayamaShingu]: { en: 'Shingu', ja: '新宮市' },
    [City.WakayamaKinokawa]: { en: 'Kinokawa', ja: '紀の川市' },
    [City.WakayamaIwade]: { en: 'Iwade', ja: '岩出市' },

    // TOTTORI
    [City.TottoriTottori]: { en: 'Tottori', ja: '鳥取市' },
    [City.TottoriYonago]: { en: 'Yonago', ja: '米子市' },
    [City.TottoriKurayoshi]: { en: 'Kurayoshi', ja: '倉吉市' },
    [City.TottoriBoundary]: { en: 'Boundary', ja: '境港市' },

    // SHIMANE
    [City.ShimaneMatsue]: { en: 'Matsue', ja: '松江市' },
    [City.ShimaneHamada]: { en: 'Hamada', ja: '浜田市' },
    [City.ShimaneIzumo]: { en: 'Izumo', ja: '出雲市' },
    [City.ShimaneMasuda]: { en: 'Masuda', ja: '益田市' },
    [City.ShimaneOda]: { en: 'Oda', ja: '大田市' },
    [City.ShimaneYasugi]: { en: 'Yasugi', ja: '安来市' },
    [City.ShimaneGotsu]: { en: 'Gotsu', ja: '江津市' },
    [City.ShimaneUnnan]: { en: 'Unnan', ja: '雲南市' },

    // OKAYAMA
    [City.OkayamaOkayama]: { en: 'Okayama', ja: '岡山市' },
    [City.OkayamaKurashiki]: { en: 'Kurashiki', ja: '倉敷市' },
    [City.OkayamaTsuyama]: { en: 'Tsuyama', ja: '津山市' },
    [City.OkayamaTamano]: { en: 'Tamano', ja: '玉野市' },
    [City.OkayamaKasaoka]: { en: 'Kasaoka', ja: '笠岡市' },
    [City.OkayamaIbara]: { en: 'Ibara', ja: '井原市' },
    [City.OkayamaSoja]: { en: 'Soja', ja: '総社市' },
    [City.OkayamaTakahashi]: { en: 'Takahashi', ja: '高梁市' },
    [City.OkayamaNiimi]: { en: 'Niimi', ja: '新見市' },
    [City.OkayamaBizen]: { en: 'Bizen', ja: '備前市' },
    [City.OkayamaSetouchi]: { en: 'Setouchi', ja: '瀬戸内市' },
    [City.OkayamaAkaiwa]: { en: 'Akaiwa', ja: '赤磐市' },
    [City.OkayamaManiwa]: { en: 'Maniwa', ja: '真庭市' },
    [City.OkayamaMimasaka]: { en: 'Mimasaka', ja: '美作市' },
    [City.OkayamaAsakuchi]: { en: 'Asakuchi', ja: '浅口市' },

    // HIROSHIMA
    [City.HiroshimaHiroshima]: { en: 'Hiroshima', ja: '広島市' },
    [City.HiroshimaKure]: { en: 'Kure', ja: '呉市' },
    [City.HiroshimaTakehara]: { en: 'Takehara', ja: '竹原市' },
    [City.HiroshimaMihara]: { en: 'Mihara', ja: '三原市' },
    [City.HiroshimaOnoichi]: { en: 'Onoichi', ja: '尾道市' },
    [City.HiroshimaFukuyama]: { en: 'Fukuyama', ja: '福山市' },
    [City.HiroshimaFuchu]: { en: 'Fuchu', ja: '府中市' },
    [City.HiroshimaMiyoshi]: { en: 'Miyoshi', ja: '三次市' },
    [City.HiroshimaShobara]: { en: 'Shobara', ja: '庄原市' },
    [City.HiroshimaOtake]: { en: 'Otake', ja: '大竹市' },
    [City.HiroshimaHigashihiroshima]: { en: 'Higashihiroshima', ja: '東広島市' },
    [City.HiroshimaHatsukaichi]: { en: 'Hatsukaichi', ja: '廿日市市' },
    [City.HiroshimaAkitakata]: { en: 'Akitakata', ja: '安芸高田市' },
    [City.HiroshimaEtajima]: { en: 'Etajima', ja: '江田島市' },

    // YAMAGUCHI
    [City.YamaguchiShimonoseki]: { en: 'Shimonoseki', ja: '下関市' },
    [City.YamaguchiUbe]: { en: 'Ube', ja: '宇部市' },
    [City.YamaguchiYamaguchi]: { en: 'Yamaguchi', ja: '山口市' },
    [City.YamaguchiHagi]: { en: 'Hagi', ja: '萩市' },
    [City.YamaguchiHofu]: { en: 'Hofu', ja: '防府市' },
    [City.YamaguchiKudamatsu]: { en: 'Kudamatsu', ja: '下松市' },
    [City.YamaguchiIwakuni]: { en: 'Iwakuni', ja: '岩国市' },
    [City.YamaguchiHikari]: { en: 'Hikari', ja: '光市' },
    [City.YamaguchiNagato]: { en: 'Nagato', ja: '長門市' },
    [City.YamaguchiYanai]: { en: 'Yanai', ja: '柳井市' },
    [City.YamaguchiMine]: { en: 'Mine', ja: '美祢市' },
    [City.YamaguchiShuto]: { en: 'Shuto', ja: '周南市' },
    [City.YamaguchiSanyo]: { en: 'Sanyo', ja: '山陽小野田市' },

    // TOKUSHIMA
    [City.TokushimaTokushima]: { en: 'Tokushima', ja: '徳島市' },
    [City.TokushimaNaruto]: { en: 'Naruto', ja: '鳴門市' },
    [City.TokushimaKomatsushima]: { en: 'Komatsushima', ja: '小松島市' },
    [City.TokushimaAnan]: { en: 'Anan', ja: '阿南市' },
    [City.TokushimaYoshinogawa]: { en: 'Yoshinogawa', ja: '吉野川市' },
    [City.TokushimaAwa]: { en: 'Awa', ja: '阿波市' },
    [City.TokushimaMima]: { en: 'Mima', ja: '美馬市' },
    [City.TokushimaMiyoshi]: { en: 'Miyoshi', ja: '三好市' },

    // KAGAWA
    [City.KagawaTakamatsu]: { en: 'Takamatsu', ja: '高松市' },
    [City.KagawaMarugame]: { en: 'Marugame', ja: '丸亀市' },
    [City.KagawaSakaide]: { en: 'Sakaide', ja: '坂出市' },
    [City.KagawaZentuji]: { en: 'Zentuji', ja: '善通寺市' },
    [City.KagawaKanonji]: { en: 'Kanonji', ja: '観音寺市' },
    [City.KagawaSanuki]: { en: 'Sanuki', ja: 'さぬき市' },
    [City.KagawaHigashikagawa]: { en: 'Higashikagawa', ja: '東かがわ市' },
    [City.KagawaMitoyo]: { en: 'Mitoyo', ja: '三豊市' },

    // EHIME
    [City.EhimeMatsuyama]: { en: 'Matsuyama', ja: '松山市' },
    [City.EhimeImabari]: { en: 'Imabari', ja: '今治市' },
    [City.EhimeUwajima]: { en: 'Uwajima', ja: '宇和島市' },
    [City.EhimeYawatahama]: { en: 'Yawatahama', ja: '八幡浜市' },
    [City.EhimeNiihama]: { en: 'Niihama', ja: '新居浜市' },
    [City.EhimeSaijo]: { en: 'Saijo', ja: '西条市' },
    [City.EhimeOzu]: { en: 'Ozu', ja: '大洲市' },
    [City.EhimeIyo]: { en: 'Iyo', ja: '伊予市' },
    [City.EhimeSeiyo]: { en: 'Seiyo', ja: '西予市' },
    [City.EhimeToon]: { en: 'Toon', ja: '東温市' },
    [City.EhimeShikokuchuo]: { en: 'Shikokuchuo', ja: '四国中央市' },

    // KOCHI
    [City.KochiKochi]: { en: 'Kochi', ja: '高知市' },
    [City.KochiMuroto]: { en: 'Muroto', ja: '室戸市' },
    [City.KochiAki]: { en: 'Aki', ja: '安芸市' },
    [City.KochiNankoku]: { en: 'Nankoku', ja: '南国市' },
    [City.KochiTosa]: { en: 'Tosa', ja: '土佐市' },
    [City.KochiSusaki]: { en: 'Susaki', ja: '須崎市' },
    [City.KochiSukumo]: { en: 'Sukumo', ja: '宿毛市' },
    [City.KochiTosashimizu]: { en: 'Tosashimizu', ja: '土佐清水市' },
    [City.KochiShimanto]: { en: 'Shimanto', ja: '四万十市' },
    [City.KochiKonan]: { en: 'Konan', ja: '香南市' },
    [City.KochiKami]: { en: 'Kami', ja: '香美市' },

    // FUKUOKA
    [City.FukuokaFukuoka]: { en: 'Fukuoka', ja: '福岡市' },
    [City.FukuokaKitakyushu]: { en: 'Kitakyushu', ja: '北九州市' },
    [City.FukuokaOmuta]: { en: 'Omuta', ja: '大牟田市' },
    [City.FukuokaKurume]: { en: 'Kurume', ja: '久留米市' },
    [City.FukuokaNogata]: { en: 'Nogata', ja: '直方市' },
    [City.FukuokaIizuka]: { en: 'Iizuka', ja: '飯塚市' },
    [City.FukuokaTagawa]: { en: 'Tagawa', ja: '田川市' },
    [City.FukuokaYanagawa]: { en: 'Yanagawa', ja: '柳川市' },
    [City.FukuokaYame]: { en: 'Yame', ja: '八女市' },
    [City.FukuokaChikugo]: { en: 'Chikugo', ja: '筑後市' },
    [City.FukuokaOkawa]: { en: 'Okawa', ja: '大川市' },
    [City.FukuokaBuzen]: { en: 'Buzen', ja: '豊前市' },
    [City.FukuokaNakagawa]: { en: 'Nakagawa', ja: '中間市' },
    [City.FukuokaOgori]: { en: 'Ogori', ja: '小郡市' },
    [City.FukuokaChikushino]: { en: 'Chikushino', ja: '筑紫野市' },
    [City.FukuokaKasuga]: { en: 'Kasuga', ja: '春日市' },
    [City.FukuokaOnojo]: { en: 'Onojo', ja: '大野城市' },
    [City.FukuokaMunakata]: { en: 'Munakata', ja: '宗像市' },
    [City.FukuokaDazaifu]: { en: 'Dazaifu', ja: '太宰府市' },
    [City.FukuokaKoga]: { en: 'Koga', ja: '古賀市' },
    [City.FukuokaFukutsu]: { en: 'Fukutsu', ja: '福津市' },
    [City.FukuokaUkiha]: { en: 'Ukiha', ja: 'うきは市' },
    [City.FukuokaMiyawaka]: { en: 'Miyawaka', ja: '宮若市' },
    [City.FukuokaKama]: { en: 'Kama', ja: '嘉麻市' },
    [City.FukuokaAsakura]: { en: 'Asakura', ja: '朝倉市' },
    [City.FukuokaMiyama]: { en: 'Miyama', ja: 'みやま市' },
    [City.FukuokaItoshima]: { en: 'Itoshima', ja: '糸島市' },

    // SAGA
    [City.SagaSaga]: { en: 'Saga', ja: '佐賀市' },
    [City.SagaKaratsu]: { en: 'Karatsu', ja: '唐津市' },
    [City.SagaTosu]: { en: 'Tosu', ja: '鳥栖市' },
    [City.SagaTaku]: { en: 'Taku', ja: '多久市' },
    [City.SagaImari]: { en: 'Imari', ja: '伊万里市' },
    [City.SagaKashima]: { en: 'Kashima', ja: '鹿島市' },
    [City.SagaOgi]: { en: 'Ogi', ja: '小城市' },
    [City.SagaUreshino]: { en: 'Ureshino', ja: '嬉野市' },
    [City.SagaKanzaki]: { en: 'Kanzaki', ja: '神埼市' },
    // PART 4 (FINAL) - Continue from Saga

    // NAGASAKI
    [City.NagasakiNagasaki]: { en: 'Nagasaki', ja: '長崎市' },
    [City.NagasakiSasebo]: { en: 'Sasebo', ja: '佐世保市' },
    [City.NagasakiShimabara]: { en: 'Shimabara', ja: '島原市' },
    [City.NagasakiIsahaya]: { en: 'Isahaya', ja: '諫早市' },
    [City.NagasakiOmura]: { en: 'Omura', ja: '大村市' },
    [City.NagasakiHirado]: { en: 'Hirado', ja: '平戸市' },
    [City.NagasakiMatsuura]: { en: 'Matsuura', ja: '松浦市' },
    [City.NagasakiTsushima]: { en: 'Tsushima', ja: '対馬市' },
    [City.NagasakiIki]: { en: 'Iki', ja: '壱岐市' },
    [City.NagasakiGoto]: { en: 'Goto', ja: '五島市' },
    [City.NagasakiSaikai]: { en: 'Saikai', ja: '西海市' },
    [City.NagasakiUnzen]: { en: 'Unzen', ja: '雲仙市' },
    [City.NagasakiMinamishimabara]: { en: 'Minamishimabara', ja: '南島原市' },

    // KUMAMOTO
    [City.KumamotoKumamoto]: { en: 'Kumamoto', ja: '熊本市' },
    [City.KumamotoYatsushiro]: { en: 'Yatsushiro', ja: '八代市' },
    [City.KumamotoHitoyoshi]: { en: 'Hitoyoshi', ja: '人吉市' },
    [City.KumamotoArao]: { en: 'Arao', ja: '荒尾市' },
    [City.KumamotoTamana]: { en: 'Tamana', ja: '玉名市' },
    [City.KumamotoAmakusa]: { en: 'Amakusa', ja: '天草市' },
    [City.KumamotoYamaga]: { en: 'Yamaga', ja: '山鹿市' },
    [City.KumamotoKikuchi]: { en: 'Kikuchi', ja: '菊池市' },
    [City.KumamotoUto]: { en: 'Uto', ja: '宇土市' },
    [City.KumamotoKamiamakusa]: { en: 'Kamiamakusa', ja: '上天草市' },
    [City.KumamotoUki]: { en: 'Uki', ja: '宇城市' },
    [City.KumamotoAsagiri]: { en: 'Asagiri', ja: '阿蘇市' },
    [City.KumamotoKosa]: { en: 'Kosa', ja: '合志市' },

    // OITA
    [City.OitaOita]: { en: 'Oita', ja: '大分市' },
    [City.OitaBeppu]: { en: 'Beppu', ja: '別府市' },
    [City.OitaNakatsu]: { en: 'Nakatsu', ja: '中津市' },
    [City.OitaHita]: { en: 'Hita', ja: '日田市' },
    [City.OitaSaiki]: { en: 'Saiki', ja: '佐伯市' },
    [City.OitaUsuki]: { en: 'Usuki', ja: '臼杵市' },
    [City.OitaTsukumi]: { en: 'Tsukumi', ja: '津久見市' },
    [City.OitaTaketa]: { en: 'Taketa', ja: '竹田市' },
    [City.OitaBungotakada]: { en: 'Bungotakada', ja: '豊後高田市' },
    [City.OitaKitsuki]: { en: 'Kitsuki', ja: '杵築市' },
    [City.OitaUsa]: { en: 'Usa', ja: '宇佐市' },
    [City.OitaBungoono]: { en: 'Bungoono', ja: '豊後大野市' },
    [City.OitaYufu]: { en: 'Yufu', ja: '由布市' },
    [City.OitaKunisaki]: { en: 'Kunisaki', ja: '国東市' },

    // MIYAZAKI
    [City.MiyazakiMiyazaki]: { en: 'Miyazaki', ja: '宮崎市' },
    [City.MiyazakiMiyakonojo]: { en: 'Miyakonojo', ja: '都城市' },
    [City.MiyazakiNobeoka]: { en: 'Nobeoka', ja: '延岡市' },
    [City.MiyazakiNichinan]: { en: 'Nichinan', ja: '日南市' },
    [City.MiyazakiKobayashi]: { en: 'Kobayashi', ja: '小林市' },
    [City.MiyazakiHyuga]: { en: 'Hyuga', ja: '日向市' },
    [City.MiyazakiKushima]: { en: 'Kushima', ja: '串間市' },
    [City.MiyazakiSaito]: { en: 'Saito', ja: '西都市' },
    [City.MiyazakiEbino]: { en: 'Ebino', ja: 'えびの市' },

    // KAGOSHIMA
    [City.KagoshimaKagoshima]: { en: 'Kagoshima', ja: '鹿児島市' },
    [City.KagoshimaKanoya]: { en: 'Kanoya', ja: '鹿屋市' },
    [City.KagoshimaMakurazaki]: { en: 'Makurazaki', ja: '枕崎市' },
    [City.KagoshimaAkune]: { en: 'Akune', ja: '阿久根市' },
    [City.KagoshimaIzumi]: { en: 'Izumi', ja: '出水市' },
    [City.KagoshimaIbusuki]: { en: 'Ibusuki', ja: '指宿市' },
    [City.KagoshimaMinamikyu]: { en: 'Minamikyu', ja: '西之表市' },
    [City.KagoshimaSoo]: { en: 'Soo', ja: '垂水市' },
    [City.KagoshimaKirishima]: { en: 'Kirishima', ja: '霧島市' },
    [City.KagoshimaIchikikushikino]: { en: 'Ichikikushikino', ja: 'いちき串木野市' },
    [City.KagoshimaSatsumasendai]: { en: 'Satsumasendai', ja: '薩摩川内市' },
    [City.KagoshimaHioki]: { en: 'Hioki', ja: '日置市' },
    [City.KagoshimaNishinoomote]: { en: 'Nishinoomote', ja: '曽於市' },
    [City.KagoshimaTarumizu]: { en: 'Tarumizu', ja: '霧島市' },
    [City.KagoshimaSatsuma]: { en: 'Satsuma', ja: '薩摩市' },
    [City.KagoshimaAmami]: { en: 'Amami', ja: '奄美市' },
    [City.KagoshimaMinamikyushu]: { en: 'Minamikyushu', ja: '南九州市' },
    [City.KagoshimaShiiba]: { en: 'Shiiba', ja: '伊佐市' },
    [City.KagoshimaAira]: { en: 'Aira', ja: '姶良市' },

    // OKINAWA
    [City.OkinawaNaha]: { en: 'Naha', ja: '那覇市' },
    [City.OkinawaGinowan]: { en: 'Ginowan', ja: '宜野湾市' },
    [City.OkinawaIshigaki]: { en: 'Ishigaki', ja: '石垣市' },
    [City.OkinawaUrasoe]: { en: 'Urasoe', ja: '浦添市' },
    [City.OkinawaItoman]: { en: 'Itoman', ja: '糸満市' },
    [City.OkinawaOkinawa]: { en: 'Okinawa', ja: '沖縄市' },
    [City.OkinawaTomigusuku]: { en: 'Tomigusuku', ja: '豊見城市' },
    [City.OkinawaUruma]: { en: 'Uruma', ja: 'うるま市' },
    [City.OkinawaMiyakojima]: { en: 'Miyakojima', ja: '宮古島市' },
    [City.OkinawaNanjo]: { en: 'Nanjo', ja: '南城市' },
    [City.OkinawaNago]: { en: 'Nago', ja: '名護市' }
}
