name: "Snapshot Tests: Vue Components"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  setup:
      name: Vue Snapshot Tests 📷
      strategy:
          matrix:
            node-version: [21.3.0]
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: Install Yarn/ Node ${{ matrix.node-version }}
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
                cache: "yarn"
          - name: Install dependencies and build
            run: |
              yarn install --immutable
              yarn ci:build

          - name: Prepare Nuxt for tests
            run: yarn prepare

      - name: Run Snapshot Tests
        id: run-tests
        run: |
          set +e
          yarn test:snapshot > snapshot-output.txt
          echo "exit_code=$?" >> $GITHUB_OUTPUT
          set -e

      - name: Comment PR on Snapshot Failure
        if: steps.snapshot.outputs.exit_code != '0'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('snapshot-output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧪 **Snapshot Test Failed**\n\n\`\`\`\n${diff.slice(0, 6500)}\n\`\`\`\n\nIf these changes are expected, run \`yarn test:snapshot:update\` and commit the updated snapshots.`
            });

