name: Typecheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  typecheck:
    name: Typecheck ✅
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12.0]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Yarn/ Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Run Typecheck
        run: yarn typecheck
